language: bash

os:
  - linux

matrix:
  include:
    - os: osx

services:
  - docker

script:
  - |
    BASHIR_VERBOSE=true ./bashir.sh --help
    [[ "$TRAVIS_OS_NAME" == 'linux' ]] && BASHIR_VERBOSE=true ./bashir.sh lint