language: bash

matrix:
  include:
    - os: linux
    - os: osx

services:
  - docker

script:
  - |
    BASHIR_VERBOSE=true ./bashir.sh --help
    if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then
      BASHIR_VERBOSE=true ./bashir.sh lint
    fi